name:  my workflow

on:  push

jobs:  
    first_job:
        runs-on:  ubuntu-latest
        steps:
            - name:  welcome message
              run:   echo "simple and easy job"

            - name: list files
              run:  ls
            
            - name: return to home dirctory
              run:  cd ..

            - name: read file
              run:  cat README.md
            
        