name:  my workflow

on:  push

jobs:  
    first_job:
        runs-on:  ubuntu-latest
        steps:
            - name: pull repo code inside runner
              uses:  actions/checkout@v4

            - name:  Run Multiable command
              run: |
                echo "simple and easy job"
                ls -ltra
                cat README.md
            - name: Generate ASCII Artwork
              run:  cowsay -f dragon "Run for the cover, Im a dragon" >> dragon.txt
            
        